Repository nspcc-dev/neofs-node, pull requests merged in 2020-10, with the labels that each got.

#62 object/transformer: Fix incorrect relation init stage
  pkg/services/object_manager/transformer/transformer.go
Labels: bug

#68 Add go pprof to neofs-storage
  cmd/neofs-node/config.go
  cmd/neofs-node/main.go
  cmd/neofs-node/pprof.go
Labels: enhancement, neofs-storage

#74 Fix order of netmap.UpdateState event argument parser
  pkg/morph/event/netmap/update_peer.go
Labels: bug, neofs-ir

#75 Fix order of update peer state method arguments
  pkg/innerring/invoke/netmap.go
Labels: bug, neofs-ir

#93 Add gRPC Reflection service
  cmd/neofs-node/config.go
  cmd/neofs-node/grpc.go
Labels: enhancement, neofs-storage

#99 Fix no-root search matcher
  pkg/services/object/search/query/v1/v1.go
Labels: bug, neofs-storage

#90 [#46] Make SELECT attribute optional
  pkg/policy/grammar.ebnf
  pkg/policy/grammar.go
  pkg/policy/query.go
  pkg/policy/query_test.go
Labels: bug

#103 Set split header in left object
  pkg/services/object_manager/transformer/transformer.go
Labels: bug, neofs-storage

#107 Pass bearer token through generated requests
  pkg/services/object/head/remote.go
  pkg/services/object/put/remote.go
  pkg/services/object/put/streamer.go
  pkg/services/object/range/remote.go
  pkg/services/object/range/streamer.go
  pkg/services/object/rangehash/remote.go
  pkg/services/object/search/remote.go
  pkg/services/object/util/prm.go
Labels: neofs-storage

#115 Check session token validity
  pkg/services/object/acl/acl.go
  pkg/services/object/acl/classifier.go
Labels: bug, neofs-storage

#123 Remove max object size value from config
  cmd/neofs-node/config.go
Labels: neofs-storage

#121 Add EACL table converter to CLI
  cmd/neofs-cli/modules/util.go
Labels: neofs-cli

#131 Implement indexing by object properties
  pkg/local_object_storage/metabase/db.go
  pkg/local_object_storage/metabase/db_test.go
  pkg/local_object_storage/metabase/put.go
  pkg/local_object_storage/metabase/select.go
Labels: enhancement

#133 Update neofs-api-go to latest version
  cmd/neofs-cli/modules/container.go
  cmd/neofs-cli/modules/object.go
  cmd/neofs-cli/modules/util.go
  go.mod
  go.sum
Labels: neofs-cli

#135 metabase: Implement benchmarking tests
  pkg/local_object_storage/metabase/delete_test.go
  pkg/local_object_storage/metabase/get_test.go
  pkg/local_object_storage/metabase/put_test.go
  pkg/local_object_storage/metabase/select_test.go
Labels: enhancement
