Repository nspcc-dev/neofs-node, pull requests merged in 2020-09, with the labels that each got.

#23 [#23] Support SQL-like queries for placement
  go.mod
  go.sum
  pkg/policy/doc.go
  pkg/policy/grammar.ebnf
  pkg/policy/grammar.go
  pkg/policy/query.go
  pkg/policy/query_test.go
Labels: enhancement

#27 Support JSON marshalers for placement policy
  pkg/policy/json.go
  pkg/policy/json_test.go
  pkg/policy/query.go
Labels: enhancement

#42 object/transformer: Fix incorrect checksums of parent object
  pkg/services/object_manager/transformer/transformer.go
Labels: bug

#44 Fix object.Head placement
  pkg/services/object/head/distributed.go
  pkg/services/object/put/streamer.go
  pkg/services/object/search/streamer.go
Labels: bug

#51 object/put: Fix incorrect splited object streaming
  pkg/services/object/put/remote.go
Labels: bug

#55 object/transformer: Fix NPE in case of empty payload
  pkg/services/object_manager/transformer/transformer.go
Labels: bug

#54 [#45] object/search: Add filtering parent objects
  pkg/services/object/search/local.go
Labels: bug, enhancement
