Repository nspcc-dev/neofs-node, pull requests merged in 2021-06, with the labels that each got.

#592 ir/container: Verify session token lifetime
  go.mod
  go.sum
  pkg/innerring/innerring.go
  pkg/innerring/processors/container/common.go
  pkg/innerring/processors/container/processor.go
Labels: bug, neofs-ir

#609 morph/client: Check return state in invoke
  pkg/morph/client/client.go
  pkg/morph/client/notary.go
Labels: bug

#617 [#88] Add relabel for instance
  config/testnet/README.md
  config/testnet/docker-compose.yml
  config/testnet/node_config.env
  config/testnet/prometheus.yml
Labels: bug

#629 Bump versions
  go.mod
  go.sum
Labels: enhancement

#635 Fix/fix double password check
  cmd/neofs-cli/modules/object.go
  cmd/neofs-cli/modules/storagegroup.go
Labels: bug, neofs-cli

#637 Fix/delete useless var in Makefile
  Makefile
Labels: refactor

#641 Fix/do not accept containers with non unique attributes
  pkg/core/container/fmt.go
  pkg/core/container/fmt_test.go
Labels: bug, neofs-ir

#642 Validate object attributes
  pkg/core/object/fmt.go
  pkg/core/object/fmt_test.go
Labels: bug, neofs-storage

#643 Refactor/Sync method names and commentaries to it
  cmd/neofs-node/reputation/intermediate/storage.go
  pkg/innerring/processors/alphabet/processor.go
  pkg/innerring/processors/audit/processor.go
  pkg/innerring/processors/governance/processor.go
  pkg/local_object_storage/blobovnicza/blobovnicza.go
  pkg/local_object_storage/blobovnicza/get_range.go
  pkg/local_object_storage/blobstor/get_small.go
  pkg/local_object_storage/blobstor/info.go
  pkg/local_object_storage/engine/range.go
  pkg/local_object_storage/metabase/movable.go
  pkg/local_object_storage/shard/move.go
  pkg/local_object_storage/shard/range.go
  pkg/local_object_storage/shard/shard.go
  pkg/morph/client/audit/wrapper/result.go
  pkg/morph/client/balance/wrapper/wrapper.go
  pkg/morph/client/container/load.go
  pkg/morph/client/container/wrapper/container.go
  pkg/morph/client/container/wrapper/wrapper.go
  pkg/morph/client/netmap/config.go
  pkg/morph/client/netmap/netmap.go
  pkg/morph/client/netmap/wrapper/snapshot.go
  pkg/morph/client/reputation/wrapper/get.go
  pkg/morph/client/reputation/wrapper/wrapper.go
  pkg/morph/client/static.go
  pkg/services/audit/taskmanager/manager.go
  pkg/services/container/announcement/load/controller/deps.go
  pkg/services/object/acl/opts.go
  pkg/services/object/delete/service.go
  pkg/services/object/search/v2/service.go
  pkg/services/object_manager/transformer/types.go
  pkg/services/reputation/eigentrust/storage/daughters/calls.go
  pkg/services/util/response/client_stream.go
  pkg/util/locode/db/boltdb/calls.go
Labels: refactor

#626 Fixed an abnormal behavior about the default config file
  cmd/neofs-cli/modules/root.go
Labels: bug

#648 morph/client: Fix method name in NewEpoch
  pkg/morph/client/netmap/new_epoch.go
Labels: bug
