Repository nspcc-dev/neofs-node, pull requests merged in 2021-04, with the labels that each got.

#454 Increase duration of notary deposit
  pkg/innerring/innerring.go
Labels: bug, neofs-ir

#456 Print transaction hashes in LE
  pkg/morph/client/client.go
  pkg/morph/client/notary.go
Labels: bug

#463 metabase: Delete graves regardless of the presence of objects
  pkg/local_object_storage/metabase/delete.go
  pkg/local_object_storage/metabase/delete_test.go
Labels: bug, neofs-storage

#469 Don't send UpdateState tx at shutdown by default
  cmd/neofs-node/config.go
  cmd/neofs-node/main.go
Labels: bug

#475 bug/ignore "already on chain" errors of notary contract
  pkg/morph/client/notary.go
Labels: help wanted

#484 Refactor/divide main reputation onto subpkgs
  cmd/neofs-node/reputation.go
  cmd/neofs-node/reputation/local/managers.go
  cmd/neofs-node/reputation/local/remote.go
  cmd/neofs-node/reputation/local/storage.go
  cmd/neofs-node/reputation/local/util.go
Labels: enhancement, neofs-storage

#487 [#458] Add supported platforms list to README
  README.md
Labels: documentation

#485 [#481] blobstor: use simplelru.LRU cache
  pkg/local_object_storage/blobstor/blobovnicza.go
Labels: bug, neofs-ir

#494 [#457] innerring: wait until notary tx persists on chain
  pkg/innerring/blocktimer.go
  pkg/innerring/innerring.go
  pkg/morph/client/client.go
  pkg/morph/client/notary.go
Labels: bug
