Repository nspcc-dev/neofs-node, pull requests merged in 2021-01, with the labels that each got.

#300 Fix status value in update peer state invocation
  pkg/innerring/invoke/netmap.go
Labels: bug

#303 morph/netmap: Implement getting network map snapshot by epoch
  pkg/morph/client/netmap/client.go
  pkg/morph/client/netmap/netmap.go
  pkg/morph/client/netmap/wrapper/netmap.go
Labels: enhancement

#319 Do not return payload formatting error on regular objects
  pkg/core/object/fmt.go
Labels: bug

#317 morph/client: Return complete eACL signature from contract
  cmd/neofs-cli/modules/container.go
  pkg/morph/client/container/eacl.go
  pkg/morph/client/container/wrapper/eacl.go
  pkg/services/container/morph/executor.go
Labels: neofs-cli, neofs-storage

#325 Fix storage node re-bootstrap approval
  pkg/innerring/processors/netmap/process_peers.go
Labels: bug, neofs-ir

#331 Increase minimal extra fee on contract invocations
  pkg/innerring/invoke/alphabet.go
  pkg/innerring/invoke/container.go
  pkg/innerring/invoke/neofs.go
  pkg/innerring/invoke/netmap.go
Labels: neofs-ir

#341 Add shell in docker images
  Dockerfile.cli
  Dockerfile.ir
  Dockerfile.storage
  Dockerfile.storage-testnet
Labels: community

#342 Fixes around Dockerfiles
  Dockerfile.cli
  Dockerfile.ir
  Dockerfile.storage
  Dockerfile.storage-testnet
Labels: enhancement

#349 innerring/audit: Use pivot in container placement
  pkg/innerring/processors/audit/process.go
Labels: bug, neofs-ir

#351 config/testnet: Add debug section in readme
  config/testnet/README.md
Labels: documentation

#350 object/acl: Make best effort to classify request
  cmd/neofs-node/object.go
  pkg/services/object/acl/classifier.go
Labels: bug, neofs-storage

#356 Fix block timer behavior after reset
  pkg/innerring/timers/block.go
  pkg/innerring/timers/block_test.go
Labels: bug
