Repository nspcc-dev/neofs-node, pull requests merged in 2021-05, with the labels that each got.

#498 skip unnecessary value
  pkg/services/audit/auditor/util.go
Labels: neofs-ir

#503 ir: Do not sync alphabet keys in sidechain-only configuration
  pkg/innerring/innerring.go
Labels: bug, neofs-ir

#511 node: Connect to main chain
  cmd/neofs-node/config.go
  cmd/neofs-node/morph.go
Labels: enhancement, neofs-storage

#534 object/hash: Fix NPE during request forwarding
  pkg/services/object/get/exec.go
  pkg/services/object/get/get.go
  pkg/services/object/get/util.go
Labels: bug, neofs-storage

#540 CLI: Rename basic ACL keywords
  cmd/neofs-cli/modules/container.go
Labels: neofs-cli

#563 Verify container operations with session token
  pkg/innerring/processors/container/common.go
  pkg/innerring/processors/container/process_container.go
  pkg/innerring/processors/container/process_eacl.go
Labels: neofs-ir
