Repository nspcc-dev/neofs-node, pull requests merged in 2022-03, with the labels that each got.

#1215 Fix typos in README
  README.md
Labels: documentation, community

#1212 Fix/NPE in multi client
  pkg/morph/client/constructor.go
  pkg/morph/client/multi.go
Labels: bug

#1223 Fix/Add `wallet` flag to adm's subnet command
  cmd/neofs-adm/internal/modules/morph/subnet.go
Labels: bug

#1242 Fix metabase put logging
  pkg/local_object_storage/metabase/put.go
Labels: bug

#1245 Feat/Add object notification to CLI
  cmd/neofs-cli/modules/object.go
Labels: neofs-cli
