Repository nspcc-dev/neofs-node, pull requests merged in 2022-06, with the labels that each got.

#1436 Feat/Log service initialization/boot up
  cmd/neofs-node/control.go
  cmd/neofs-node/main.go
  cmd/neofs-node/metrics.go
  cmd/neofs-node/morph.go
  cmd/neofs-node/pprof.go
Labels: enhancement, neofs-storage

#1441 Fix/Do not validate subnet removal
  pkg/innerring/processors/subnet/delete.go
  pkg/innerring/processors/subnet/delete_test.go
  pkg/innerring/subnet.go
Labels: bug, neofs-ir

#1489 neofs-adm: include alphabet contracts to the group
  cmd/neofs-adm/internal/modules/morph/initialize_deploy.go
Labels: bug, neofs-adm

#1497 Fix changelog
  CHANGELOG.md
Labels: documentation

#1509 Feat/Log WS client closing error
  pkg/morph/client/multi.go
Labels: enhancement

#1507 Fix/Do not handle object concurrently by the policer
  CHANGELOG.md
  pkg/services/policer/policer.go
  pkg/services/policer/process.go
Labels: bug, neofs-storage

#1542 [#1307] neofs-adm: Add tests for `morph init` command
  cmd/neofs-adm/internal/modules/morph/generate_test.go
  cmd/neofs-adm/internal/modules/morph/initialize_test.go
Labels: neofs-adm
