Repository nspcc-dev/neofs-node, pull requests merged in 2022-01, with the labels that each got.

#1071 Fix missing response status at ACL problems
  cmd/neofs-node/object.go
Labels: bug, neofs-storage

#1072 Fix missing body and meta header on empty Object.Search results
  pkg/services/object/transport_splitter.go
Labels: bug, neofs-storage

#1076 Read IR list from role management contract w/o mainchain
  pkg/innerring/innerring.go
Labels: bug, neofs-ir

#1087 Upd/Update `neofs-sdk-go`
  cmd/neofs-cli/internal/client/client.go
  cmd/neofs-cli/internal/client/prm.go
  cmd/neofs-cli/modules/container.go
  cmd/neofs-cli/modules/control.go
  cmd/neofs-cli/modules/root.go
  cmd/neofs-node/container.go
  cmd/neofs-node/object.go
  cmd/neofs-node/reputation/common/remote.go
  cmd/neofs-node/reputation/intermediate/remote.go
  cmd/neofs-node/reputation/internal/client/client.go
  cmd/neofs-node/reputation/local/remote.go
  go.mod
  go.sum
  pkg/core/client/client.go
  pkg/innerring/internal/client/client.go
  pkg/innerring/rpc.go
  pkg/network/cache/client.go
  pkg/network/cache/multi.go
  pkg/services/object/get/prm.go
  pkg/services/object/get/service.go
  pkg/services/object/get/util.go
  pkg/services/object/get/v2/util.go
  pkg/services/object/head/remote.go
  pkg/services/object/internal/client/client.go
  pkg/services/object/put/prm.go
  pkg/services/object/put/service.go
  pkg/services/object/put/streamer.go
  pkg/services/object/put/v2/streamer.go
  pkg/services/object/search/prm.go
  pkg/services/object/search/service.go
  pkg/services/object/search/util.go
  pkg/services/object/search/v2/util.go
Labels: neofs-cli, neofs-ir, neofs-storage, refactor

#1099 object/search: Fix error loss in `SignService.Search`
  pkg/services/object/sign.go
Labels: bug, neofs-storage

#1100 Upd/Adopt new SDK's `owner.ID` API
  cmd/neofs-adm/internal/modules/morph/subnet.go
  cmd/neofs-cli/modules/accounting.go
  cmd/neofs-cli/modules/container.go
  cmd/neofs-cli/modules/object.go
  cmd/neofs-node/config.go
  cmd/neofs-node/object.go
  go.mod
  go.sum
  pkg/core/container/fmt_test.go
  pkg/core/object/fmt.go
  pkg/core/object/fmt_test.go
  pkg/innerring/processors/container/common.go
  pkg/innerring/processors/settlement/audit/calculate.go
  pkg/innerring/processors/settlement/basic/context.go
  pkg/innerring/settlement.go
  pkg/innerring/subnet.go
  pkg/local_object_storage/engine/engine_test.go
  pkg/local_object_storage/metabase/db_test.go
  pkg/local_object_storage/shard/shard_test.go
  pkg/services/object/acl/acl.go
  pkg/services/object/acl/classifier.go
Labels: refactor

#1091 Do not cut `data` args in `NNS`
  cmd/neofs-adm/internal/modules/morph/initialize_deploy.go
Labels: neofs-adm

#1112 ir/container: Fix check of `SetEACL` operation
  pkg/innerring/processors/container/process_eacl.go
Labels: bug, neofs-ir

#1120 Fix/Printing config file in `verbose` mode
  cmd/neofs-cli/modules/accounting.go
  cmd/neofs-cli/modules/control.go
  cmd/neofs-cli/modules/root.go
  cmd/neofs-cli/modules/util.go
Labels: bug, neofs-cli
