Repository nspcc-dev/neofs-node, pull requests merged in 2022-12, with the labels that each got.

#2148 Add metric `readonly` to get shards mode
  CHANGELOG.md
  pkg/local_object_storage/engine/metrics.go
  pkg/local_object_storage/engine/shards.go
  pkg/local_object_storage/shard/metrics_test.go
  pkg/local_object_storage/shard/mode.go
  pkg/local_object_storage/shard/shard.go
  pkg/metrics/object.go
Labels: hot

#2159 Feat/Add tree replication timeout configuration
  CHANGELOG.md
  cmd/neofs-node/config/tree/config.go
  cmd/neofs-node/config/tree/config_test.go
  cmd/neofs-node/tree.go
  config/example/node.env
  config/example/node.json
  config/example/node.yaml
  pkg/services/tree/options.go
  pkg/services/tree/replicator.go
  pkg/services/tree/service.go
Labels: neofs-storage, hot

#2162 services/tree: close connection after the syncronization
  CHANGELOG.md
  pkg/services/tree/sync.go
Labels: bug, hot

#2139 object/put: use `sync.Pool` for temporary payloads
  CHANGELOG.md
  pkg/services/object/put/distributed.go
  pkg/services/object/put/pool.go
  pkg/services/object/put/streamer.go
Labels: hot

#2142 Fix/Shard mode switch
  CHANGELOG.md
  pkg/local_object_storage/shard/delete.go
  pkg/local_object_storage/shard/exists.go
  pkg/local_object_storage/shard/gc.go
  pkg/local_object_storage/shard/get.go
  pkg/local_object_storage/shard/inhume.go
  pkg/local_object_storage/shard/list.go
  pkg/local_object_storage/shard/lock.go
  pkg/local_object_storage/shard/move.go
  pkg/local_object_storage/shard/put.go
  pkg/local_object_storage/shard/range.go
  pkg/local_object_storage/shard/select.go
  pkg/local_object_storage/shard/tree.go
Labels: hot
