Repository nspcc-dev/neofs-node, pull requests merged in 2022-11, with the labels that each got.

#2037 (SUPPORT) services/object: Fix concurrent map writes in traverser
  CHANGELOG.md
  pkg/services/object/put/distributed.go
Labels: bug, neofs-storage, P0

#2074 [SUPPORT] Fix/Write-cache flush duplication
  CHANGELOG.md
  pkg/local_object_storage/writecache/flush.go
Labels: bug, neofs-storage, P2, 2022Q4

#2063 Support new hash format in morph nns client
  CHANGELOG.md
  cmd/neofs-adm/internal/modules/morph/initialize_nns.go
  pkg/morph/client/nns.go
Labels: bug, P2

#2078 adm: Pack parameters for `setPrice` invocation
  CHANGELOG.md
  cmd/neofs-adm/internal/modules/morph/initialize_deploy.go
Labels: bug, P2

#2104 Fix/OID signature in CLI output
  CHANGELOG.md
  cmd/neofs-cli/modules/object/head.go
Labels: bug, neofs-cli, P2
