Repository nspcc-dev/neofs-node, pull requests merged in 2023-05, with the labels that each got.

#2335 Fix/NPE panic on tree services connection close
  CHANGELOG.md
  pkg/services/tree/cache.go
Labels: bug, neofs-storage

#2336 Fix/Do not lose small objects on WC errors
  CHANGELOG.md
  pkg/local_object_storage/writecache/put.go
Labels: bug, neofs-storage

#2342 Upd/Go version to `1.18`
  .docker/Dockerfile.adm
  .docker/Dockerfile.cli
  .docker/Dockerfile.ir
  .docker/Dockerfile.storage
  .docker/Dockerfile.storage-testnet
  .github/workflows/go.yml
  .github/workflows/run-tests.yml
  CHANGELOG.md
  Makefile
  go.mod
  go.sum
  pkg/local_object_storage/blobstor/blobovniczatree/blobovnicza.go
  pkg/local_object_storage/engine/delete_test.go
  pkg/local_object_storage/writecache/storage.go
  pkg/morph/client/client.go
  pkg/morph/client/netmap/config.go
  pkg/morph/client/notary.go
  pkg/morph/client/static.go
  pkg/services/accounting/response.go
  pkg/services/accounting/sign.go
  pkg/services/container/announcement/load/controller/controller.go
  pkg/services/container/announcement/load/route/placement/builder.go
  pkg/services/container/announcement/load/route/router.go
  pkg/services/container/response.go
  pkg/services/container/sign.go
  pkg/services/control/ir/server/server.go
  pkg/services/netmap/response.go
  pkg/services/netmap/sign.go
  pkg/services/object/acl/acl.go
  pkg/services/object/acl/v2/request.go
  pkg/services/object/acl/v2/service.go
  pkg/services/object/acl/v2/types.go
  pkg/services/object/acl/v2/util.go
  pkg/services/object/put/pool.go
  pkg/services/object/response.go
  pkg/services/object/sign.go
  pkg/services/object/util/chain.go
  pkg/services/session/response.go
  pkg/services/session/sign.go
  pkg/services/util/response/client_stream.go
  pkg/services/util/response/unary.go
  pkg/services/util/sign.go
  pkg/util/http/server.go
  pkg/util/locode/db/airports/db.go
  pkg/util/locode/db/boltdb/db.go
  pkg/util/locode/db/continents/geojson/db.go
  pkg/util/locode/table/csv/table.go
Labels: refactor, go

#2339 Fix/Iterating over just removed objects in FSTree
  CHANGELOG.md
  pkg/local_object_storage/blobstor/fstree/fstree.go
  pkg/local_object_storage/blobstor/internal/blobstortest/iterate.go
  pkg/local_object_storage/writecache/flush.go
  pkg/local_object_storage/writecache/iterate.go
Labels: bug, neofs-storage

#2340 Upd/Generics have landed
  CHANGELOG.md
  cmd/neofs-node/cache.go
  go.mod
  go.sum
  pkg/innerring/processors/neofs/process_assets.go
  pkg/innerring/processors/neofs/processor.go
  pkg/local_object_storage/blobstor/blobovniczatree/blobovnicza.go
  pkg/local_object_storage/blobstor/blobovniczatree/control.go
  pkg/local_object_storage/blobstor/blobovniczatree/delete.go
  pkg/local_object_storage/blobstor/blobovniczatree/get.go
  pkg/local_object_storage/blobstor/blobovniczatree/get_range.go
  pkg/local_object_storage/writecache/storage.go
  pkg/morph/client/client.go
  pkg/morph/client/constructor.go
  pkg/morph/client/notary.go
  pkg/services/object_manager/placement/netmap.go
  pkg/services/object_manager/tombstone/checker.go
  pkg/services/object_manager/tombstone/constructor.go
  pkg/services/policer/policer.go
  pkg/services/policer/process.go
  pkg/services/tree/cache.go
  pkg/services/tree/container.go
Labels: refactor

#2358 Fix/Morph and metrics panics
  pkg/metrics/metrics.go
  pkg/morph/client/constructor.go
Labels: bug, hot

#2357 cli: drop support for binary keys, use wallets
  CHANGELOG.md
  cmd/neofs-cli/internal/commonflags/flags.go
  cmd/neofs-cli/internal/key/key_test.go
  cmd/neofs-cli/internal/key/raw.go
  cmd/neofs-cli/internal/key/wallet.go
Labels: neofs-cli, security
