Repository nspcc-dev/neofs-node, pull requests merged in 2025-03, with the labels that each got.

#3187 Checksum-related fixes for SearchV2 metabase migration
  CHANGELOG.md
  pkg/local_object_storage/metabase/metadata.go
  pkg/local_object_storage/metabase/metadata_test.go
  pkg/local_object_storage/metabase/version.go
Labels: bug, neofs-storage

#3205 Fix failing notary retries
  CHANGELOG.md
  pkg/morph/client/notary.go
  pkg/morph/event/notary_preparator.go
Labels: bug, neofs-ir

#3218 ir: drop annoying "new transaction callback finished with error" log
  CHANGELOG.md
  pkg/innerring/internal/blockchain/blockchain.go
Labels: bug
